<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VCDA.FinancialManager.Domain\VCDA.FinancialManager.Domain.csproj" />
    <ProjectReference Include="..\VCDA.FinancialManager.Application\VCDA.FinancialManager.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
